# Compose file to run Schemathesis tests against the API.
version: "3"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.e2e.api
    ports:
      - "8080:8080"

  test:
    build:
      context: ./
      dockerfile: Dockerfile.e2e.schema
    tty: true
    depends_on:
      - api
    links:
      - api
