# fly.toml app configuration file generated for medama-core on 2024-01-24T16:58:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "medama-core"
primary_region = "lhr"

[env]
PORT = "8080"
APP_DATABASE_HOST = "/db/sqlite.db"
ANALYTICS_DATABASE_HOST = "/db/analytics.db"

[http_service]
internal_port = 8080
force_https = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[mounts]
source = "medama_db"
destination = "/db"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
