# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  dev:
    deps: [generate]
    cmds:
      - go run -tags "sqlite_foreign_keys" ./cmd/ {{.CLI_ARGS}} -debug
    env:
      GOEXPERIMENT: loopvar

  build:
    deps: [generate]
    cmds:
      - go build -tags "sqlite_foreign_keys" -o ./bin/main ./cmd/
    env:
      CGO_ENABLED: "1"
      GOEXPERIMENT: loopvar

  release:
    deps: [generate]
    cmds:
      - go build -tags "sqlite_foreign_keys" -o ./main -ldflags "-s -w" ./cmd/
    env:
      CGO_ENABLED: "1"
      GOEXPERIMENT: loopvar

  generate:
    aliases: [gen]
    cmds:
      - go generate ./...
    sources:
      - ./openapi.yaml
      - ./.ogen.yml
      - ./generate.go
      - ./generate.sh
    generates:
      - ./api/**/*.go

  update:
    aliases: [upgrade]
    cmds:
      - go get -u ./...
      - go mod tidy

  lint:
    cmds:
      - golangci-lint run ./... --fix

  coverage:
    cmds:
      - go-acc ./... -o coverage.out
      - go tool cover -html=coverage.out

  e2e:
    cmds:
      - docker compose -f compose-test.yaml up --abort-on-container-exit --build

  test:
    deps: [generate]
    cmds:
      - go test -v ./... -tags "sqlite_foreign_keys"
    env:
      CGO_ENABLED: "1"
      GOEXPERIMENT: loopvar
