name: Tests
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - "core/**"

  push:
    branches: [main]
    paths:
      - "core/**"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2

      - uses: actions/setup-go@v5
        with:
          go-version-file: core/go.mod
          cache: false

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          working-directory: core
          # Disable godox linter to hide TODO warnings
          args: --disable godox
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: core

    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2

      - uses: actions/setup-go@v5
        with:
          go-version-file: core/go.mod
          cache-dependency-path: core/go.sum

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: task build

      - name: Test
        run: task test
